// Generated by gencpp from file Jared/simpleMoteus.msg
// DO NOT EDIT!


#ifndef JARED_MESSAGE_SIMPLEMOTEUS_H
#define JARED_MESSAGE_SIMPLEMOTEUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Jared
{
template <class ContainerAllocator>
struct simpleMoteus_
{
  typedef simpleMoteus_<ContainerAllocator> Type;

  simpleMoteus_()
    : position(0.0)
    , velocity(0.0)
    , torque(0.0)  {
    }
  simpleMoteus_(const ContainerAllocator& _alloc)
    : position(0.0)
    , velocity(0.0)
    , torque(0.0)  {
  (void)_alloc;
    }



   typedef double _position_type;
  _position_type position;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _torque_type;
  _torque_type torque;





  typedef boost::shared_ptr< ::Jared::simpleMoteus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Jared::simpleMoteus_<ContainerAllocator> const> ConstPtr;

}; // struct simpleMoteus_

typedef ::Jared::simpleMoteus_<std::allocator<void> > simpleMoteus;

typedef boost::shared_ptr< ::Jared::simpleMoteus > simpleMoteusPtr;
typedef boost::shared_ptr< ::Jared::simpleMoteus const> simpleMoteusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Jared::simpleMoteus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Jared::simpleMoteus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Jared::simpleMoteus_<ContainerAllocator1> & lhs, const ::Jared::simpleMoteus_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.torque == rhs.torque;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Jared::simpleMoteus_<ContainerAllocator1> & lhs, const ::Jared::simpleMoteus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Jared

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::Jared::simpleMoteus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Jared::simpleMoteus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Jared::simpleMoteus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Jared::simpleMoteus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Jared::simpleMoteus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Jared::simpleMoteus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Jared::simpleMoteus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e433883cdedcd3f2276d926b28334eb4";
  }

  static const char* value(const ::Jared::simpleMoteus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe433883cdedcd3f2ULL;
  static const uint64_t static_value2 = 0x276d926b28334eb4ULL;
};

template<class ContainerAllocator>
struct DataType< ::Jared::simpleMoteus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Jared/simpleMoteus";
  }

  static const char* value(const ::Jared::simpleMoteus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Jared::simpleMoteus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 position\n"
"float64 velocity\n"
"float64 torque\n"
;
  }

  static const char* value(const ::Jared::simpleMoteus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Jared::simpleMoteus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.torque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simpleMoteus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Jared::simpleMoteus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Jared::simpleMoteus_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<double>::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "torque: ";
    Printer<double>::stream(s, indent + "  ", v.torque);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JARED_MESSAGE_SIMPLEMOTEUS_H
